---
title: ""
output: 
  html_document:
   toc: true
   toc_float: true
   theme: flatly
---

```{r setup, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
knitr::opts_chunk$set(warning = F, message = F)
```
<br>

# <span class="glyphicon glyphicon-calendar" aria-hidden="false"></span> Course Schedule
Below is our course schedule, which will almost certainly change as the course progresses.  Details regarding evaluation due dates can be found below the table.

```{r, echo=FALSE}
library(tidyverse)
library(kableExtra)
options(knitr.kable.NA = '')

my_backgrounds <- colorRampPalette(c("white", "cadetblue"))(5)
row_nums <-seq(1,26,2)

summercourseschedule <- read_csv("Summer2025_schedule - Sheet1.csv")
knitr::kable(summercourseschedule[1:26,]) %>%
  kable_styling(full_width = T, position = "float_left")   %>%
  row_spec(row_nums ,background = my_backgrounds[2])


```

 



Assignments are to be submitted via Crowdmark.

<!-- # ```{r, echo=FALSE} -->
<!-- # library(tidyverse) -->
<!-- # library(kableExtra) -->
<!-- # options(knitr.kable.NA = '') -->
<!-- #  -->
<!-- # my_backgrounds <- colorRampPalette(c("white", "gray"))(5) -->
<!-- # k = 6  -->
<!-- # row_nums <-c(rbind(1+4*(0:k), 2+4*(0:k))) -->
<!-- #  -->
<!-- # jsc270courseassschedule <- read_csv("Winter2022_assignment_schedule.csv") -->
<!-- # knitr::kable(jsc270courseassschedule[1:26,])  %>%  -->
<!-- #    kable_styling(full_width = T, position = "float_left")   %>%  -->
<!-- #   row_spec(row_nums,background = my_backgrounds[2])  -->
<!-- # ``` -->

<!-- <br> -->
